{"uuid": "183033f3-ae53-46de-972e-e1c61c69e405", "children": ["a1de65d2-7d18-4640-949e-29927e9af165"], "befores": [{"name": "session_action", "status": "broken", "statusDetails": {"message": "PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'D:\\\\B2B\\\\OutPuts\\\\log\\\\Web_Autotest_2019-11-20 1541.log'\n", "trace": "  File \"E:\\Python3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\Python3\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\Python3\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"D:\\B2B\\Testcases\\conftest.py\", line 24, in session_action\n    remove_files_in_dir(contants.reports_log)\n  File \"D:\\B2B\\common\\delete_history.py\", line 12, in remove_files_in_dir\n    os.remove(c_path)\n"}, "start": 1574235676545, "stop": 1574235676548}], "start": 1574235676545, "stop": 1574235676622}