{"uuid": "72a8d185-394d-4f0a-a3ea-7ce298bd213b", "children": ["ace61eb6-0863-40d5-b3d7-5d7d26369cef"], "befores": [{"name": "session_action", "status": "broken", "statusDetails": {"message": "PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'D:\\\\B2B\\\\OutPuts\\\\log\\\\Web_Autotest_2019-11-20 1528.log'\n", "trace": "  File \"E:\\Python3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\Python3\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\Python3\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"D:\\B2B\\Testcases\\conftest.py\", line 24, in session_action\n    remove_files_in_dir(contants.reports_log)\n  File \"D:\\B2B\\common\\delete_history.py\", line 12, in remove_files_in_dir\n    os.remove(c_path)\n"}, "start": 1574234922105, "stop": 1574234922224}], "start": 1574234922105, "stop": 1574234922364}